version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"  # Cambiado de 8080 a 8081
    volumes:
      - .:/var/www/html/  # Monta el directorio actual en /var/www/html
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: instituto_tecnologico
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  db:
    image: mysql:8.0
    container_name: mysql_db_siiv20
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_DATABASE: instituto_tecnologico 
      MYSQL_USER: agencia_user       
      MYSQL_PASSWORD: 123456         
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3309"  # Cambiado de 3306 a 3307

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8087:80"  # Cambiado de 8086 a 8087
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    restart: always

volumes:
  db_data: